AWSTemplateFormatVersion: '2010-09-09'
Description: "Vulnerability Test Resource - Infrastructure Layer"

Resources:
  # ❌ 脆弱性: 過剰な権限 (Wildcard Permissions)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WildcardPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  # ❌ 脆弱性: 暗号化なし・バックアップなしのDB
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "VulnerableUserTable"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: false

  # ❌ 脆弱性: 公開設定・暗号化なしのS3
  DebugLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "debug-logs-${AWS::AccountId}"
      AccessControl: PublicRead # 古い形式の公開設定

  # ❌ 脆弱性: 認証なし・古いTLSポリシーのAPI
  UserApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "VulnerableUserAPI"

  CustomDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: "api.vulnerable-example.com"
      SecurityPolicy: TLS_1_0 # ❌ 脆弱な古いプロトコル
      CertificateArn: "arn:aws:acm:ap-northeast-1:123456789012:certificate/dummy"

  # ❌ 脆弱性: HTTPS強制なしのCloudFront
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: allow-all # ❌ HTTPを許可